### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by farhadsoft** [farhadsoft/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by farhadsoft** [comment]
Donald Trump
[Facebook](https://www.fb.com/DonaldTrump)
[Twitter](https://twitter.com/realDonaldTrump)
[Instagram](https://www.instagram.com/realDonaldTrump/)

**Comment by farhad-su** [comment]
**Farhad Mammadov**
Junior .NET Developer

[Facebook](https://www.fb.com/www.farhad.su)
[Twitter](https://twitter.com/farhad_su)
[Instagram](https://www.instagram.com/farhad.su/)
Phone number: +380674785059
