### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by farhadsoft** [farhadsoft/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by farhadsoft** [comment]
Languages

🇷🇺 РУССКИЙ 🇺🇸 ENGLISH
Skills

NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING FOR TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIAN
Character

ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING
Likes😃

BILLIONS FILET-O-FISH BIG MAC CHINA QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY [1] [2]
Dislikes😞

DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS
Wants🥺

BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO GOLF MORE OFTEN WIN ALL THE COURT SUITS
Education

    2011
Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!

**Comment by farhad-su** [comment]
Skills

Cloud Technologies:

AWS EC2 AWS VPC AWS Route53 AWS S3 Azure Compute Azure App Service
System Administration:

Windows Linux [Ubuntu, Debian, Centos] Active Directory
Web technologies:

HTML CSS Bootstrap PHP C# .NET
Databases:

SQL Server MySQL SQLite
Additional hard skills:

Git [Gitlab, GitHub] VirtualBox
Likes

Sports [CrossFit, Swimming, Soccer] Travel Walking
